//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdenSunAPI.DAL.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdenSunEntities : DbContext
    {
        public AdenSunEntities()
            : base("name=AdenSunEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adress_T> Adress_T { get; set; }
        public virtual DbSet<Delivery_T> Delivery_T { get; set; }
        public virtual DbSet<Department_T> Department_T { get; set; }
        public virtual DbSet<Discount_T> Discount_T { get; set; }
        public virtual DbSet<Item_T> Item_T { get; set; }
        public virtual DbSet<ItemCategory_T> ItemCategory_T { get; set; }
        public virtual DbSet<Order_T> Order_T { get; set; }
        public virtual DbSet<OrderItem_T> OrderItem_T { get; set; }
        public virtual DbSet<Region_T> Region_T { get; set; }
        public virtual DbSet<ShoppingCart_T> ShoppingCart_T { get; set; }
        public virtual DbSet<ShoppingCartItem_T> ShoppingCartItem_T { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User_T> User_T { get; set; }
        public virtual DbSet<UserReview_T> UserReview_T { get; set; }
    }
}
