//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdenSunAPI.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_T
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_T()
        {
            this.OrderItem_T = new HashSet<OrderItem_T>();
        }
    
        public int OrderID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsValid { get; set; }
        public Nullable<System.DateTime> ValidationDate { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<int> DeliveryID { get; set; }
        public int UserID { get; set; }
    
        public virtual Delivery_T Delivery_T { get; set; }
        public virtual User_T User_T { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem_T> OrderItem_T { get; set; }
    }
}
