//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdenSunAPI.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCartItem_T
    {
        public int ShoppingCartItemID { get; set; }
        public int ItemID { get; set; }
        public int ShoppingCartID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Item_T Item_T { get; set; }
        public virtual ShoppingCart_T ShoppingCart_T { get; set; }
    }
}
