//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdenSunAPI.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_T
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_T()
        {
            this.Order_T = new HashSet<Order_T>();
            this.ShoppingCart_T = new HashSet<ShoppingCart_T>();
            this.UserReview_T = new HashSet<UserReview_T>();
        }
    
        public int UserID { get; set; }
        public string Mail { get; set; }
        public string Password { get; set; }
        public bool IsProfessional { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int AdressID { get; set; }
    
        public virtual Adress_T Adress_T { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_T> Order_T { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart_T> ShoppingCart_T { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserReview_T> UserReview_T { get; set; }
    }
}
